steps:
  - name: gcr.io/cloud-builders/gsutil
    id: 'download_manifest'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gsutil cp gs://dbth_bucket/manifest.json ./state

  - id: "DBT RUN"
    name: "python:3.10-slim"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cat ./state/manifest.json
        python -m pip install --upgrade pip
        pip install dbt-core
        pip install dbt-clickhouse
        dbt run --target dev --select state:modified+ --defer --state ./state
    waitFor: ['download_manifest']

options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
  objects:
    location: 'gs://dbth_bucket/'
    paths: ["target/manifest.json"]