steps:
  - id: "DOWNLOAD MANIFEST"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gsutil cp gs://dbth_bucket/manifest.json ./state

  - id: "DBT RUN"
    name: "python:3.10-slim"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-clickhouse
        dbt run --target dev --select state:modified+ --defer --state ./state
    waitFor: ['DOWNLOAD_MANIFEST']

options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
  objects:
    location: 'gs://dbth_bucket/'
    paths: ["target/manifest.json"]