steps:
  - id: "DOWNLOAD MANIFEST"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      file_path=gs://dbth_bucket/full_build/manifest.json
      gsutil -q stat $file_path
      status=$?

      if [[ $status == 0 ]]; then
        gsutil cp gs://dbth_bucket/full_build/manifest.json ./state
      else
        echo "Manifest File does not exist. Continuing with the build."
      fi
      

  - id: "DBT RUN"
    name: "python:3.10-slim"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-clickhouse
        dbt run $_DBT_RUN_PARAMETERS
        dbt docs generate
    waitFor: ['DOWNLOAD MANIFEST']

  - id: "UPLOAD OUTPUTS"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        gsutil cp ./target/catalog.json gs://dbth_bucket/full_build/
        gsutil cp ./target/index.html gs://dbth_bucket/full_build/
    waitFor: ['DBT RUN']

options:
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: '$_ARTIFACTS_LOCATION'
    paths: ["target/manifest.json"]
