steps:
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gsutil cat -r 10-100 gs://dbth_bucket/manifest.json
      gsutil -m cp -r 'gs://dbth_bucket/manifest.json' '.'

  - id: "DBT RUN"
    name: "python:3.10-slim"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        python -m pip install --upgrade pip
        pip install dbt-core
        pip install dbt-clickhouse
        dbt run --target dev --select state:modified+
options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
  objects:
    location: 'gs://dbth_bucket/'
    paths: ["target/manifest.json"]