steps:
  - id: "DBT RUN"
    name: "python:3.10-slim"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cat ./target/manifest.json

options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
  objects:
    location: 'gs://dbth_bucket/'
    paths: ["target/manifest.json"]