steps:
  - id: "DBT RUN"
    name: "python:3.10-slim"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        python -m pip install --upgrade pip
        pip install dbt-core
        pip install dbt-clickhouse
        dbt run --target dev --select state:modified+ --defer --state target/manifest.json
options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
  objects:
    location: 'gs://dbth_bucket/'
    paths: ["target/manifest.json"]