
version: 2

models:
  - name: zz_test_model_one
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: zz_test_model_two
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: zz_test_model_three
    description: "fruits table"
    columns:
      - name: fname
        description: "fruit name"

  - name: zz_test_model_four
    description: "animal table"
    columns:
      - name: fname
        description: "animal name"
